trigger:
  batch: true
  branches:
    include:
      - "*"
resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: GitHub (SFA)
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/heads/master
    endpoint: GitHub (SFA)
  pipelines:
    - pipeline: das-employer-config
      project: Digital Apprenticeship Service
      source: das-employer-config
      branch: master
pr:
  - master

variables:
  - group: RELEASE Management Resources
  - group: RELEASE das-levy-transfer-matching-api

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: RELEASE das-levy-transfer-matching-api
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      DeploymentApprovals: AT
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/LevyTransferMatchingApi/SFA.DAS.LevyTransferMatching.Api.zip