trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
  - name: SolutionBaseName
    value: SFA.DAS.LevyTransferMatching.Api
  - name: DACPACSolutionBaseName
    value: SFA.DAS.LevyTransferMatching.Database
  - name: BuildConfiguration
    value: release
  - name: BuildPlatform
    value: any cpu
  - group: RELEASE Management Resources
  - group: RELEASE das-levy-transfer-matching-api
      
resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: GitHub (SFA)
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/heads/DASD-8734_Array_Handling
    endpoint: GitHub (SFA)
  pipelines:
    - pipeline: das-employer-config
      project: Digital Apprenticeship Service
      source: das-employer-config
      branch: master

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)
  - template: pipeline-templates/job/dacpac-build.yml
    parameters:
      SolutionBaseName: $(DACPACSolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: RELEASE das-levy-transfer-matching-api
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM