trigger:
  batch: true
  branches:
    include:
      - "*"

pool:
  name: DAS - Continuous Integration
  workspace:
    clean: all

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/master
    endpoint: GitHub (SFA)
  pipelines:
    - pipeline: das-employer-config
      project: Digital Apprenticeship Service
      source: das-employer-config
      branch: master
pr:
  - master

variables:
  - group: RELEASE Management Resources
  - group: RELEASE das-levy-transfer-matching-api

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  pool:
    name: DAS - Continuous Deployment
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-levy-transfer-matching-api
  jobs:
  - template: pipeline-templates/job/arm-deploy.yml
    parameters:
      ServiceConnection: SFA-DAS-DevTest-ARM
      SubscriptionId: $(SubscriptionId)
      Location: $(ResourceGroupLocation)
      Environment: DEV
      TemplatePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.json
      ParametersPath: $(Pipeline.Workspace)/ToolsSupportArtifacts/azure/template.parameters.json
      TemplateSecrets:
        LoggingRedisConnectionString: $(LoggingRedisConnectionString)
        ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        CommitmentsClientApiConfigurationClientSecret: $(CommitmentsClientApiConfigurationClientSecret)
  - template: pipeline-templates/job/app-role-assignments.yml
    parameters:
      Environment: DEV
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
      Tenant: $(Tenant)
  - template: pipeline-templates/job/web-deploy.yml
    parameters:
      DeploymentApprovals: DEV
      ServiceConnection: SFA-DAS-DevTest-ARM
      DeploymentPackagePath: $(Pipeline.Workspace)/ToolsSupportArtifacts/SFA.DAS.Tools.Support.Web.zip
