jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration
  variables:
  - group: Prod Management Resources
  - name: buildConfiguration
    value: release
  workspace:
    clean: all
  steps:
  - task: UseGitVersion@5
    displayName: GitVersion
    inputs:
      versionSpec: 5.x
      useConfigFile: true
      configFilePath: GitVersion.yml

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: Publish Levy Transfer Matching Api
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.LevyTransferMatching.Api/SFA.DAS.LevyTransferMatching.Api.csproj
      arguments: --configuration release --output $(build.artifactstagingdirectory)/publish --no-restore --no-build

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact - LevyTransferMatchingApi
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: LevyTransferMatchingApi