parameters:  
  Environment:
  ServiceConnection:
  - name: RunBlockOnPossibleDataLoss
    type: boolean
    default: false

jobs:
- job: waitForValidation
  displayName: Wait for external validation
  pool: server
  timeoutInMinutes: 5 
  steps:
  - task: ManualValidation@0
    condition: eq(parameters.RunBlockOnPossibleDataLoss, true)
    timeoutInMinutes: 5 
    inputs:
      instructions: 'Please validate the build configuration and resume'
      onTimeout: 'reject'
- deployment: DeployWebApp
  pool:
    name: DAS - Continuous Deployment Agents
  environment: ${{ parameters.Environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: azure-pipelines-templates/deploy/step/set-backendaccessrestrictions-variable.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SharedEnvResourceGroup: $(SharedEnvResourceGroup)
            SharedEnvVirtualNetworkName : $(SharedEnvVirtualNetworkName)
            BackEndAccessRestrictionsExcludedSubnets: $(BackEndAccessRestrictionsExcludedSubnets)
            ResourceEnvironmentName: $(ResourceEnvironmentName)
            UnrestrictedEnvironments: $(UnrestrictedEnvironments)
            UptimeMonitoringAccessRestrictions: $(UptimeMonitoringAccessRestrictions)
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SubscriptionId: $(SubscriptionId)
            Location: $(ResourceGroupLocation)
            Environment: ${{ parameters.Environment }}
            TemplatePath: $(Pipeline.Workspace)/LevyTransferMatchingApi/azure/template.json
            ParametersPath: $(Pipeline.Workspace)/LevyTransferMatchingApi/azure/template.parameters.json
            IsMultiRepoCheckout: true
            TemplateSecrets:
              LoggingRedisConnectionString: $(LoggingRedisConnectionString)
              ConfigurationStorageConnectionString: $(ConfigurationStorageConnectionString)
        - template: azure-pipelines-templates/deploy/step/generate-config.yml@das-platform-building-blocks
          parameters:
            ServiceConnection: ${{ parameters.ServiceConnection }}
            SourcePath: $(Pipeline.Workspace)/das-employer-config/Configuration/das-levy-transfer-matching-api
            TargetFileName: '*.schema.json'
            TableName: Configuration
        - task: ManualValidation@0
          condition:  and(eq(parameters.Environment, 'AT'), eq(parameters.RunBlockOnPossibleDataLoss, true))
          timeoutInMinutes: 5
          inputs:
            instructions: '/p:BlockOnPossibleDataLoss=false will run for SQL DACPAC deployment. Are you sure you want to continue?'
            onTimeout: 'reject'
        - template: azure-pipelines-templates/deploy/step/sql-dacpac-deploy.yml@das-platform-building-blocks
          parameters:
            AzureSubscription: ${{ parameters.ServiceConnection }}
            ServerName: $(SharedSQLServerFQDN)
            DatabaseName: $(DatabaseName)
            SqlUsername: $(SharedSQLServerUsername)
            SqlPassword: $(SharedSQLServerPassword)
            DacpacFile: $(Pipeline.Workspace)/DacpacArtifact/src/SFA.DAS.LevyTransferMatching.Database/bin/Output/SFA.DAS.LevyTransferMatching.Database.dacpac
            AdditionalArguments: ${{ parameters.RunBlockOnPossibleDataLoss }}

        # - template: azure-pipelines-templates/deploy/step/app-deploy.yml@das-platform-building-blocks
        #   parameters:
        #     ServiceConnection: ${{ parameters.ServiceConnection }}
        #     AppServiceName: $(ApiAppServiceName)
        #     DeploymentPackagePath: $(Pipeline.Workspace)/LevyTransferMatchingApi/SFA.DAS.LevyTransferMatching.Api.zip